
# Mapping of curl error codes to their descriptions
curl_error_mapping = {
    1: "Unsupported protocol",
    2: "Failed to initialize",
    3: "URL malformed",
    4: "URL user malformatted",
    5: "Couldn't resolve proxy",
    6: "Couldn't resolve host",
    7: "Failed to connect to host",
    8: "FTP weird server reply",
    9: "FTP access denied",
    10: "FTP user/password incorrect",
    11: "FTP weird PASS reply",
    12: "FTP weird USER reply",
    13: "FTP weird PASV reply",
    14: "FTP weird 227 format",
    15: "FTP can't get host",
    16: "HTTP/2 error",
    17: "FTP couldn't set binary",
    18: "Partial file",
    19: "FTP couldn't download/access to the given file",
    20: "FTP write error",
    21: "FTP quote error",
    22: "HTTP page not retrieved",
    23: "Write error",
    25: "FTP couldn't STOR file",
    26: "Read error",
    27: "Out of memory",
    28: "Operation timeout",
    30: "FTP PORT failed",
    31: "FTP couldn't use REST",
    33: "HTTP range error",
    34: "HTTP post error",
    35: "SSL/TLS handshake fail",
    36: "FTP bad download resume",
    37: "FILE couldn't read file",
    38: "LDAP cannot bind",
    39: "LDAP search failed",
    41: "Function not found",
    42: "Aborted by callback",
    43: "Internal error",
    45: "Interface error",
    47: "Too many redirects",
    48: "Unknown TELNET option",
    49: "Malformed telnet option",
    51: "The peer's SSL certificate or SSH MD5 fingerprint was not OK",
    52: "The server didn't reply anything, which in this context is an error",
    53: "SSL crypto engine not found",
    54: "Cannot set SSL crypto engine as default",
    55: "Failed sending network data",
    56: "Failure in receiving network data",
    58: "Problem with the local certificate",
    59: "Couldn't use the specified SSL cipher",
    # 60: "Peer certificate cannot be authenticated with known CA certificates",
    60: "Certificate not verified with known CAs",
    61: "Unrecognized transfer encoding",
    62: "Invalid LDAP URL",
    63: "Maximum file size exceeded",
    64: "Requested FTP SSL level failed",
    65: "Sending the data requires a rewind that failed",
    66: "Failed to initialise SSL Engine",
    67: "The user name, password, or similar was not accepted and curl failed to log in",
    68: "File not found on TFTP server",
    69: "Permission problem on TFTP server",
    70: "Out of disk space on TFTP server",
    71: "Illegal TFTP operation",
    72: "Unknown TFTP transfer ID",
    73: "File already exists (TFTP)",
    74: "No such user (TFTP)",
    75: "Character conversion failed",
    76: "Character conversion functions required",
    77: "Problem with reading the SSL CA cert",
    78: "The resource referenced in the URL does not exist",
    79: "An unspecified error occurred during the SSH session",
    80: "Failed to shut down the SSL connection",
    82: "Could not load CRL file, missing or wrong format",
    83: "Issuer check failed",
    84: "The FTP PRET command failed",
    85: "RTSP: mismatch of CSeq numbers",
    86: "RTSP: mismatch of Session Identifiers",
    87: "unable to parse FTP file list",
    88: "FTP chunk callback reported error",
    89: "No connection available, the session will be queued",
    90: "SSL public key does not matched pinned public key"
}

# Mapping of HTTP status codes to their descriptions
http_status_descriptions = {
    400: 'Bad Request',
    401: 'Unauthorized',
    403: 'Forbidden',
    404: 'Not Found',
    405: 'Method Not Allowed',
    406: 'Not Acceptable',
    407: 'Proxy Authentication Required',
    408: 'Request Timeout',
    409: 'Conflict',
    410: 'Gone',
    500: 'Internal Server Error',
    501: 'Not Implemented',
    502: 'Bad Gateway',
    503: 'Service Unavailable',
    504: 'Gateway Timeout',
    505: 'HTTP Version Not Supported'
}
